# Generated by Django 3.2.25 on 2025-10-04 19:54

import bson.objectid
from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_auto_20250810_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=djongo.models.fields.ObjectIdField(auto_created=True, db_column='_id', default=bson.objectid.ObjectId, primary_key=True, serialize=False),
        ),
    ]
