# Generated by Django 3.2.25 on 2025-10-16 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_auto_20251015_1340'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='user',
            name='user_is_dele_0a42d6_idx',
        ),
        migrations.RemoveField(
            model_name='user',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_deleted',
        ),
    ]
