# Generated by Django 3.2.25 on 2025-08-12 13:07

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('category', models.CharField(blank=True, max_length=60)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='technology',
            index=models.Index(fields=['slug'], name='technology__slug_7702f0_idx'),
        ),
        migrations.AddIndex(
            model_name='technology',
            index=models.Index(fields=['name'], name='technology__name_addcfa_idx'),
        ),
    ]
