# Generated by Django 3.2.25 on 2025-08-20 08:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('technology', '0005_extra_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='technology',
            options={'ordering': ('-created_at',)},
        ),
        migrations.RemoveIndex(
            model_name='technology',
            name='technology__slug_7702f0_idx',
        ),
        migrations.RemoveIndex(
            model_name='technology',
            name='technology__name_addcfa_idx',
        ),
        migrations.RemoveField(
            model_name='technology',
            name='category',
        ),
        migrations.RemoveField(
            model_name='technology',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='technology',
            name='attributes_and_performance',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='technology',
            name='challenges_and_current_status',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='technology',
            name='confidentiality',
            field=models.CharField(choices=[('C1', 'C1 – Public'), ('C2', 'C2 – Internal'), ('C3', 'C3 – Confidential')], default='C2', max_length=2),
        ),
        migrations.AddField(
            model_name='technology',
            name='desc_and_applications',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='technology',
            name='enabling_technologies',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='technology',
            name='evaluation_history',
            field=models.TextField(blank=True, default='[]'),
        ),
        migrations.AddField(
            model_name='technology',
            name='gallery',
            field=models.TextField(blank=True, default='[]'),
        ),
        migrations.AddField(
            model_name='technology',
            name='initial_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='technology',
            name='last_modified',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='technology',
            name='macro',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='technology',
            name='meso1',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='technology',
            name='meso2',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='technology',
            name='publications_and_projects',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='technology',
            name='strategic_value_and_evaluation',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='technology',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='technology',
            name='extra_fields',
            field=models.TextField(blank=True, default='[]'),
        ),
        migrations.AlterField(
            model_name='technology',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterModelTable(
            name='technology',
            table='technology_technology',
        ),
    ]
