# Generated by Django 3.2.25 on 2025-10-04 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technology', '0006_auto_20250820_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technology',
            name='confidentiality',
            field=models.CharField(choices=[('C1', 'C1 – Public'), ('C2', 'C2 – Confidential'), ('C3C', 'C3 – Civil'), ('C3M', 'C3 – Military')], default='C1', max_length=4),
        ),
    ]
