# Generated by Django 3.2.25 on 2025-10-15 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technology', '0007_alter_technology_confidentiality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technology',
            name='confidentiality',
            field=models.CharField(choices=[('C1', 'C1-PUBLIC'), ('C2', 'C2-CONFIDENTIAL'), ('C3C', 'C3-STRATEGIC (CIVIL)'), ('C3M', 'C3-STRATEGIC (MILITARY)')], default='C1', max_length=4),
        ),
    ]
