# Generated by Django 3.2.25 on 2025-10-29 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technology', '0008_alter_technology_confidentiality'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technology',
            name='is_active',
        ),
        migrations.AddField(
            model_name='technology',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('dormant', 'Dormant')], default='active', max_length=20),
        ),
    ]
